General:
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"

  save_path: "$(arg save_path)"
  previous_map: "$(arg previous_map_str)"
  bagname: "$(arg bagname)"
  is_save_map: 0

  lidar_type: 0
  blind: 0.3 # 0.5
  point_filter_num: 3
  extrinsic_tran: [-0.011, -0.02329, 0.04412]
  extrinsic_rota: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
Odometry:
  max_init: 30
  cov_gyr: 0.1
  cov_acc: 1
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  # down_size: 0.5
  down_size: 0.1
  dept_err: 0.02
  beam_err: 0.05
  # voxel_size: 4
  voxel_size: 1
  min_eigen_value: 0.0025
  degrade_bound: 10
  point_notime: 0

LocalBA:
  win_size: 3 # earlier BTC, more sensitive, but noisier descriptors
  max_layer: 2
  cov_gyr: 0.01
  cov_acc: 2
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  min_ba_point: 1
  plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
  imu_coef: 0.0002
  thread_num: 5

Loop:
  jud_default: 0.45
  icp_eigval: 6 # Lower â†’ more passes, but also more wrong matches.
  ratio_drift: 0.01

GBA:
  voxel_size: 2
  min_eigen_value: 0.01
  eigen_value_array: [4.0, 4.0, 4.0, 4.0]
  total_max_iter: 6